# Generated by Django 4.0.6 on 2022-12-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(default='aaa', max_length=42, primary_key=True, serialize=False, unique=True)),
                ('wallet_balance', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('wallet_address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.wallet')),
            ],
        ),
    ]
