# Generated by Django 4.0.6 on 2022-12-15 17:38

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(default=account.models.generate_address, max_length=42, primary_key=True, serialize=False, unique=True)),
                ('wallet_balance', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('wallet_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.wallet')),
            ],
        ),
    ]
