# Generated by Django 4.0.8 on 2022-12-07 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.wallet'),
        ),
    ]
