# Generated by Django 4.0.6 on 2022-12-09 13:55

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default=account.models.generate_address, max_length=42, primary_key=True, serialize=False, unique=True),
        ),
    ]
