# Generated by Django 4.0.6 on 2022-12-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('creator_fee', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('image_url', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('history', models.CharField(max_length=100)),
                ('chain', models.CharField(max_length=100)),
                ('last_sale', models.DateTimeField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to='account.user')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='account.user')),
            ],
        ),
    ]
