# Generated by Django 4.0.6 on 2023-01-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='history',
        ),
    ]
