# Generated by Django 4.0.8 on 2022-12-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email_alter_user_username_and_more'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('value', models.FloatField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_fee', models.IntegerField()),
                ('gas_price', models.FloatField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to='account.user')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to='account.user')),
                ('token_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.nft')),
            ],
        ),
    ]
