# Generated by Django 4.0.6 on 2022-12-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('market', '0002_remove_transaction_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_id_f', to='market.nft')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_f', to='account.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user_id', 'nft_id'), name='unique_follow'),
        ),
    ]
