# Generated by Django 4.0.8 on 2022-12-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_follow_follow_unique_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
