# Generated by Django 4.0.6 on 2022-12-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_follow_follow_unique_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='previous_trans_id',
            field=models.IntegerField(default=-1),
        ),
    ]
