# Generated by Django 4.0.6 on 2022-12-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_transaction_previous_trans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='previous_trans_id',
        ),
    ]
